const actions = {
  GET_TODO_LIST: "GET_TODO_LIST",
  GET_TODO_LIST_SUCCESS: "GET_TODO_LIST_SUCCESS",
  GET_TODO_LIST_FAILURE: "GET_TODO_LIST_FAILURE",
  GET_TODO_LIST_RESET: "GET_TODO_LIST_RESET",

  ADD_TODO_ITEM: "ADD_TODO_ITEM",
  ADD_TODO_ITEM_SUCCESS: "ADD_TODO_ITEM_SUCCESS",
  ADD_TODO_ITEM_FAILURE: "ADD_TODO_ITEM_FAILURE",
  ADD_TODO_ITEM_RESET: "ADD_TODO_ITEM_RESET",

  UPDATE_TODO_ITEM: "UPDATE_TODO_ITEM",
  UPDATE_TODO_ITEM_SUCCESS: "UPDATE_TODO_ITEM_SUCCESS",
  UPDATE_TODO_ITEM_FAILURE: "UPDATE_TODO_ITEM_FAILURE",
  UPDATE_TODO_ITEM_RESET: "UPDATE_TODO_ITEM_RESET",

  DELETE_TODO_ITEM: "DELETE_TODO_ITEM",
  DELETE_TODO_ITEM_SUCCESS: "DELETE_TODO_ITEM_SUCCESS",
  DELETE_TODO_ITEM_FAILURE: "DELETE_TODO_ITEM_FAILURE",
  DELETE_TODO_ITEM_RESET: "DELETE_TODO_ITEM_RESET",

  add_todos: (data) => ({
    type: actions.ADD_TODO_ITEM,
    payload: data,
  }),

  get_todos: () => ({
    type: actions.GET_TODO_LIST,
  }),
};

export default actions;
